### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by brobare** [tbotnz/netpalm-flask-hello-cdp-world#1]
git clone https://github.com/tbotnz/netpalm-flask-hello-cdp-world.git && cd netpalm-hello-cdp-world

Seems like it should be:
git clone https://github.com/tbotnz/netpalm-flask-hello-cdp-world.git && cd netpalm-flask-hello-cdp-world

**Comment by tbotnz** [comment]
You are right, cheers

Updated
